name: Python CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest

    - name: Checkout full repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        export PATH="$HOME/.local/share/heroku/bin:$PATH"


    # - name: Deploy to Heroku
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     curl https://cli-assets.heroku.com/install.sh | sh
    #     heroku auth:token
    #     heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
    #     git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:main

    - name: Push to Heroku
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
        git push heroku HEAD:main --force
